### What is OneHot Encoding
*   a method of converting categorical variables into a format that machine learning models can easily understand and use. ![Picture1.png]()

## How to implement

### Option 1: OneHotEncoder

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
df = pd.read_csv("https://raw.githubusercontent.com/ywen2021/CPSC392/main/Data/boutique.csv")
df

,year,gender,age,height_cm,waist_size_cm,inseam_cm,test_group,salary_self_report_in_k,months_active,num_purchases,amount_spent_annual
0,2020,woman,34.0,168,98,75.0,0,69.83,21,89,729.73
1,2020,man,28.0,168,88,76.0,0,61.39,7,32,621.73
2,2021,woman,18.0,170,95,75.0,0,80.55,2,25,820.82
3,2021,woman,43.0,167,97,75.0,0,82.98,4,89,880.33
4,2021,other,29.0,173,89,74.0,0,62.00,5,95,690.35
...,...,...,...,...,...,...,...,...,...,...,...
24995,2022,woman,28.0,170,96,76.0,1,75.86,3,20,859.94
24996,2022,woman,18.0,166,97,71.0,1,80.79,17,17,1064.67
24997,2019,woman,21.0,170,93,74.0,1,77.29,16,97,1000.02
24998,2022,woman,33.0,172,103,72.0,1,79.32,1,21,858.48
24999,2021,woman,47.0,159,90,75.0,1,72.07,12,88,1047.39

In [ ]:
categorical_features = [ "test_group","gender"]
onehot=OneHotEncoder(sparse_output=False)
one_hot_encoded = onehot.fit_transform(df[categorical_features])
# Convert to a DataFrame for easier interpretation
encoded_df = pd.DataFrame(one_hot_encoded, columns=onehot.get_feature_names_out([ "test_group","gender"]))

# Concatenate the encoded columns with the original DataFrame
df_encoded = pd.concat([df, encoded_df], axis=1)

df_encoded

,year,gender,age,height_cm,waist_size_cm,inseam_cm,test_group,salary_self_report_in_k,months_active,num_purchases,amount_spent_annual,test_group_0,test_group_1,gender_man,gender_nonbinary,gender_other,gender_woman
0,2020,woman,34.0,168,98,75.0,0,69.83,21,89,729.73,1.0,0.0,0.0,0.0,0.0,1.0
1,2020,man,28.0,168,88,76.0,0,61.39,7,32,621.73,1.0,0.0,1.0,0.0,0.0,0.0
2,2021,woman,18.0,170,95,75.0,0,80.55,2,25,820.82,1.0,0.0,0.0,0.0,0.0,1.0
3,2021,woman,43.0,167,97,75.0,0,82.98,4,89,880.33,1.0,0.0,0.0,0.0,0.0,1.0
4,2021,other,29.0,173,89,74.0,0,62.00,5,95,690.35,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,2022,woman,28.0,170,96,76.0,1,75.86,3,20,859.94,0.0,1.0,0.0,0.0,0.0,1.0
24996,2022,woman,18.0,166,97,71.0,1,80.79,17,17,1064.67,0.0,1.0,0.0,0.0,0.0,1.0
24997,2019,woman,21.0,170,93,74.0,1,77.29,16,97,1000.02,0.0,1.0,0.0,0.0,0.0,1.0
24998,2022,woman,33.0,172,103,72.0,1,79.32,1,21,858.48,0.0,1.0,0.0,0.0,0.0,1.0
24999,2021,woman,47.0,159,90,75.0,1,72.07,12,88,1047.39,0.0,1.0,0.0,0.0,0.0,1.0

In [ ]:
df_encoded=df_encoded.drop(columns=["test_group", "gender"])
df_encoded

,year,age,height_cm,waist_size_cm,inseam_cm,salary_self_report_in_k,months_active,num_purchases,amount_spent_annual,test_group_0,test_group_1,gender_man,gender_nonbinary,gender_other,gender_woman
0,2020,34.0,168,98,75.0,69.83,21,89,729.73,1.0,0.0,0.0,0.0,0.0,1.0
1,2020,28.0,168,88,76.0,61.39,7,32,621.73,1.0,0.0,1.0,0.0,0.0,0.0
2,2021,18.0,170,95,75.0,80.55,2,25,820.82,1.0,0.0,0.0,0.0,0.0,1.0
3,2021,43.0,167,97,75.0,82.98,4,89,880.33,1.0,0.0,0.0,0.0,0.0,1.0
4,2021,29.0,173,89,74.0,62.00,5,95,690.35,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,2022,28.0,170,96,76.0,75.86,3,20,859.94,0.0,1.0,0.0,0.0,0.0,1.0
24996,2022,18.0,166,97,71.0,80.79,17,17,1064.67,0.0,1.0,0.0,0.0,0.0,1.0
24997,2019,21.0,170,93,74.0,77.29,16,97,1000.02,0.0,1.0,0.0,0.0,0.0,1.0
24998,2022,33.0,172,103,72.0,79.32,1,21,858.48,0.0,1.0,0.0,0.0,0.0,1.0
24999,2021,47.0,159,90,75.0,72.07,12,88,1047.39,0.0,1.0,0.0,0.0,0.0,1.0

## Option 2: Using get_dummies

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/ywen2021/CPSC392/main/Data/boutique.csv")
df_encoded=pd.get_dummies(df,columns=[ "test_group","gender"],dtype=int)
df_encoded

,year,age,height_cm,waist_size_cm,inseam_cm,salary_self_report_in_k,months_active,num_purchases,amount_spent_annual,test_group_0,test_group_1,gender_man,gender_nonbinary,gender_other,gender_woman
0,2020,34.0,168,98,75.0,69.83,21,89,729.73,1,0,0,0,0,1
1,2020,28.0,168,88,76.0,61.39,7,32,621.73,1,0,1,0,0,0
2,2021,18.0,170,95,75.0,80.55,2,25,820.82,1,0,0,0,0,1
3,2021,43.0,167,97,75.0,82.98,4,89,880.33,1,0,0,0,0,1
4,2021,29.0,173,89,74.0,62.00,5,95,690.35,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,2022,28.0,170,96,76.0,75.86,3,20,859.94,0,1,0,0,0,1
24996,2022,18.0,166,97,71.0,80.79,17,17,1064.67,0,1,0,0,0,1
24997,2019,21.0,170,93,74.0,77.29,16,97,1000.02,0,1,0,0,0,1
24998,2022,33.0,172,103,72.0,79.32,1,21,858.48,0,1,0,0,0,1
24999,2021,47.0,159,90,75.0,72.07,12,88,1047.39,0,1,0,0,0,1